modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/daedalus4096/PrimalMagic/issues"
license="MIT License"

[[mods]]
modId="primalmagick"
version="${file.jarVersion}"
displayName="Primal Magick - Archaic"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/primal-magick"
logoFile="primalmagick_archaic_icon.png"
credits="Thanks to Lorelli, Quinloki, and DaRetroThaumaturge for the art!"
authors="Daedalus4096"
description='''Harness the magic of the primal sources of the land.'''

[[dependencies.primalmagick]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
